"""
Генератор выходных файлов:
- VLESS_WORKING.txt      — все рабочие конфиги
- VLESS_ONLY.txt         — только VLESS
- VMESS_ONLY.txt         — только VMess
- TROJAN_ONLY.txt        — только Trojan
- HYSTERIA_ONLY.txt      — Hysteria2 / hy2
- TOP50.txt              — топ-50 по задержке
- stats.json             — машиночитаемая статистика
"""

import json
import logging
import re
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import unquote
from zoneinfo import ZoneInfo

log = logging.getLogger("writer")

OUTPUT_DIR = Path(__file__).parent.parent / "output"


# ── Вспомогательные ─────────────────────────────────────────────────────────────

def _clean_label(cfg: str, latency: int, geo: dict) -> str:
    """Формирует читаемую метку для конфига."""
    base, _, label = cfg.partition("#")
    label = unquote(label).strip()
    # Убираем старые латентности
    label = re.sub(r"\s*\|\s*\d+ms", "", label)
    # Убираем старые флаги в начале если добавим новый
    flag = geo.get("flag", "🌐")
    country = geo.get("country", "")
    city = geo.get("city", "")
    tls_mark = geo.get("tls_ok_mark", "")

    if country and country != "Unknown":
        loc = f"{flag} {country}"
        if city:
            loc += f" ({city})"
    elif label:
        loc = label
    else:
        loc = "server"

    return f"{base}#{loc}{tls_mark} | {latency}ms"


def _header(title: str, count: int, now_msk: datetime) -> str:
    now_utc = datetime.now(timezone.utc)
    return "\n".join([
        f"# profile-title: {title}",
        f"# profile-update-interval: 1",
        f"# Date/Time: {now_utc.strftime('%Y-%m-%d')} / {now_msk.strftime('%H:%M')} (Moscow)",
        f"# Количество: {count}",
        f"# Generated by: vless-collector (GitHub Actions)",
        "",
    ])


# ── Основная функция ─────────────────────────────────────────────────────────────

def write_all_outputs(
    working: list[tuple[str, int]],
    geo_map: dict[str, dict] | None = None,
    tls_map: dict[str, bool] | None = None,
):
    """
    working  — список (config_string, latency_ms)
    geo_map  — dict: host → {country, country_code, city, org, flag}
    tls_map  — dict: host → tls_ok (bool)
    """
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    now_msk = datetime.now(ZoneInfo("Europe/Moscow"))
    geo_map  = geo_map  or {}
    tls_map  = tls_map  or {}

    # ── Категории ────────────────────────────────────────────────────────────────
    buckets: dict[str, list[tuple[str, int]]] = {
        "all":      [],
        "vless":    [],
        "vmess":    [],
        "trojan":   [],
        "hysteria": [],
        "ss":       [],
        "other":    [],
    }

    # Счётчики для статистики
    country_stats: dict[str, int] = {}
    tls_confirmed = 0

    for cfg, lat in working:
        low = cfg.lower()
        # Определяем протокол
        if low.startswith("vless://"):
            buckets["vless"].append((cfg, lat))
        elif low.startswith("vmess://"):
            buckets["vmess"].append((cfg, lat))
        elif low.startswith("trojan://"):
            buckets["trojan"].append((cfg, lat))
        elif low.startswith("hysteria2://") or low.startswith("hy2://"):
            buckets["hysteria"].append((cfg, lat))
        elif low.startswith("ss://"):
            buckets["ss"].append((cfg, lat))
        else:
            buckets["other"].append((cfg, lat))
        buckets["all"].append((cfg, lat))

        # Гео-статистика
        from urllib.parse import urlparse
        try:
            host = urlparse(cfg).hostname or ""
        except Exception:
            host = ""
        geo = geo_map.get(host, {})
        cc = geo.get("country", "Unknown")
        country_stats[cc] = country_stats.get(cc, 0) + 1

        if tls_map.get(host):
            tls_confirmed += 1

    # ── Записываем файлы ─────────────────────────────────────────────────────────

    files_info = [
        ("VLESS_WORKING.txt", "all",      "✅ All Working Servers | Auto-collected"),
        ("VLESS_ONLY.txt",    "vless",    "🔷 VLESS Only | Auto-collected"),
        ("VMESS_ONLY.txt",    "vmess",    "🔶 VMess Only | Auto-collected"),
        ("TROJAN_ONLY.txt",   "trojan",   "🐴 Trojan Only | Auto-collected"),
        ("HYSTERIA_ONLY.txt", "hysteria", "⚡ Hysteria2 Only | Auto-collected"),
        ("SS_ONLY.txt",       "ss",       "🔲 Shadowsocks Only | Auto-collected"),
    ]

    written: dict[str, int] = {}
    for filename, bucket_key, title in files_info:
        entries = buckets[bucket_key]
        if not entries:
            continue

        lines = [_header(f"{title} | {now_msk.strftime('%Y-%m-%d %H:%M')} MSK", len(entries), now_msk)]

        for cfg, lat in entries:
            try:
                from urllib.parse import urlparse
                host = urlparse(cfg).hostname or ""
            except Exception:
                host = ""
            geo = geo_map.get(host, {})
            geo["tls_ok_mark"] = " 🔒" if tls_map.get(host) else ""
            line = _clean_label(cfg, lat, geo)
            lines.append(line)

        path = OUTPUT_DIR / filename
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        written[filename] = len(entries)
        log.info("💾  %-25s  %d конфигов", filename, len(entries))

    # ── TOP-50 ──────────────────────────────────────────────────────────────────
    top50 = buckets["all"][:50]
    if top50:
        lines = [_header(f"🏆 TOP-50 Fastest | {now_msk.strftime('%Y-%m-%d %H:%M')} MSK", len(top50), now_msk)]
        for cfg, lat in top50:
            try:
                from urllib.parse import urlparse
                host = urlparse(cfg).hostname or ""
            except Exception:
                host = ""
            geo = geo_map.get(host, {})
            geo["tls_ok_mark"] = " 🔒" if tls_map.get(host) else ""
            lines.append(_clean_label(cfg, lat, geo))
        (OUTPUT_DIR / "TOP50.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
        log.info("💾  %-25s  %d конфигов", "TOP50.txt", len(top50))

    # ── stats.json ──────────────────────────────────────────────────────────────
    latencies = [lat for _, lat in buckets["all"]]
    stats = {
        "updated_utc":     datetime.now(timezone.utc).isoformat(),
        "updated_msk":     now_msk.isoformat(),
        "total_working":   len(buckets["all"]),
        "tls_confirmed":   tls_confirmed,
        "by_protocol": {
            "vless":    len(buckets["vless"]),
            "vmess":    len(buckets["vmess"]),
            "trojan":   len(buckets["trojan"]),
            "hysteria": len(buckets["hysteria"]),
            "ss":       len(buckets["ss"]),
            "other":    len(buckets["other"]),
        },
        "latency": {
            "min_ms":  min(latencies) if latencies else 0,
            "avg_ms":  sum(latencies) // len(latencies) if latencies else 0,
            "max_ms":  max(latencies) if latencies else 0,
            "p50_ms":  sorted(latencies)[len(latencies) // 2] if latencies else 0,
            "p90_ms":  sorted(latencies)[int(len(latencies) * 0.9)] if latencies else 0,
        },
        "top_countries": dict(
            sorted(country_stats.items(), key=lambda x: -x[1])[:15]
        ),
        "files": written,
    }

    stats_path = OUTPUT_DIR / "stats.json"
    stats_path.write_text(json.dumps(stats, ensure_ascii=False, indent=2), encoding="utf-8")
    log.info("💾  %-25s  записан", "stats.json")

    return stats
